spring:
  application:
    name: Champions-League

  datasource:
    url: jdbc:postgresql://dpg-d7v0rmflk1mc73as7dmg-a:5432/champions_db_ykj3
    driver-class-name: org.postgresql.Driver
    username: champions_db_ykj3_user
    password: Q8CrSSkfySPajR9alMmkpkk3eKV6VeYP


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
